#!/bin/bash
set -ue

# PORT="$1"
# MODEL="$2"
MODE=${MODE:-vanilla}
NAME=${NAME:-llama-server-vanilla-both}
SINGLE=${SINGLE:-0}

LAYERS=${LAYERS:-0}
CTX=${CTX:-65024}
(( CTX < 1024 )) && CTX=$(( CTX * 1000 ))

RUNNER=docker
[[ -f /usr/bin/podman ]] && RUNNER=podman

MODEL_PATH=$(realpath "$MODEL")
MODEL_FOLDER=${MODEL_PATH%/*}
MODEL=${MODEL_PATH##*/}

docker pull ghcr.io/ggml-org/llama.cpp:full-cuda

CONTAINER_ARGS=(
  run -it --rm
  --name $NAME
  -e UID=1000
  -e GID=1000
  -e APP_UID=1000
  -e APP_GID=1000
  -p 0.0.0.0:${PORT}:8799
  -v "$MODEL_FOLDER":/models:ro
  # --entrypoint /bin/bash
)

hostname
case `hostname` in
"noir")
  echo "## NOIR"
  ALIAS=${ALIAS:-noir-model}
  ;;
"station")
  echo "## STAION"
  ALIAS=station-model
  ALIAS=${ALIAS:-station-model}
  ;;
"cosmo")
  RUNNER=docker
  [[ "$SINGLE" == "1" ]] || {
    CONTAINER_ARGS+=(--gpus all)
  }
  ALIAS=${ALIAS:-cosmo-both}
  LAYERS=99
  ;;
esac

LLAMA_ARGS=(
  --model /models/$MODEL
  --alias $ALIAS
  --port 8799
  --host 0.0.0.0
  # --n-gpu-layers $LAYERS
  --batch-size  2048
  --ubatch-size 128
  --cache-type-k q8_0
  --cache-type-v q8_0
  --cont-batching
  --ctx-size $CTX
  --flash-attn on
  --jinja
  --parallel 1
  --threads `cat /proc/cpuinfo | grep MHz | wc -l`
  --kv-offload
  # --verbose --metrics
  # --temp 0.75 --top_p 0.95 --min-p 0.01   # --top_k 40
  # --temp 0.60 --top_k 0
  --temp 0.6 --top-p 0.95 --top-k 0 --min-p 0.01
  --cache-ram 16384
)

case $MODE in
"ikllm")
  CONTAINER=ikllm:latest
  ;;
"vanilla")
  CONTAINER=ghcr.io/ggml-org/llama.cpp:full-cuda
  CONTAINER_ARGS+=(--entrypoint /app/llama-server)
  LLAMA_ARGS+=(--mmap)
  LLAMA_ARGS+=(--fit on --main-gpu 1)
  ;;
*)
  echo "[FATAL] bad MODE: $MODE"
  exit 1
esac

echo
echo "## Detected settiongs:
PORT:  $PORT
MODEL: $MODEL
MODE:  $MODE
NAME:  $NAME
ALIAS: $ALIAS
"
function run_model() {
  echo
  echo "## Run model-holder"
  echo "./bin/model-holder $MODEL_PATH"

  echo
  echo "## Running $CONTAINER"
  echo "$RUNNER" "${CONTAINER_ARGS[@]}" "$CONTAINER" "${LLAMA_ARGS[@]}"
  "$RUNNER" "${CONTAINER_ARGS[@]}" "$CONTAINER" "${LLAMA_ARGS[@]}"

  # "$RUNNER" "${CONTAINER_ARGS[@]}" --entrypoint /bin/bash "$CONTAINER"
  # "$RUNNER" "${CONTAINER_ARGS[@]}" --entrypoint /app/llama-bench "$CONTAINER" --n-gpu-layers 99 --batch-size 4096 --cache-type-k q8_0 --cache-type-v q8_0 --flash-attn 1 --threads 32 --ubatch-size 512 --model /models/$MODEL
}
