#!/bin/bash
CTX=8192
export CTX=16384
# export MODEL="$1"
export MODEL=models/gguf/Qwen3-VL-8B-Instruct-UD-Q4_K_XL.gguf

export PORT=8701
export NAME=llama-server-4060
export ALIAS=cosmo-4060
export SINGLE=1
source ./run-common

CONTAINER_ARGS+=(--gpus '"device=1"')
run_model_vision
