#!/bin/bash
LAYERS=99
MODEL=Qwen3-8B-Q4_K_S.gguf
MODEL=Qwen2.5-Coder-14B-Instruct-Q4_K_M.gguf
MODEL=Ministral-3-14B-Instruct-2512-UD-Q3_K_XL.gguf

docker run -it --rm \
  --name ikllm-both \
  --gpus all \
  -e UID=1000 \
  -e GID=1000 \
  -e APP_UID=1000 \
  -e APP_GID=1000 \
  -p 0.0.0.0:8799:8080 \
  -v /mnt/noir/scratch/ai/llm/models:/models:ro \
  --entrypoint /app/llama-bench \
  ghcr.io/ggml-org/llama.cpp:full-cuda --model /models/$MODEL \
  --batch-size  4096 \
  --cache-type-k q8_0 \
  --cache-type-v q8_0 \
  --n-gpu-layers $LAYERS \
  --ubatch-size 512 \
  --mmap \
  --jinja \
  --flash-attn on \
  --threads `cat /proc/cpuinfo | grep MHz | wc -l`
